version: '3.7'

services:
  # Servicio de MariaDB
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: tu_password_root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: tu_password_wordpress
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork

  # Servicio de WordPress
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: tu_password_wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    extra_hosts:
      - "sso.narval.es:host-gateway"
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - mynetwork

  # Servicio de Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: wordpress
      DB_USER: wordpress
      DB_PASSWORD: tu_password_wordpress
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    #command: start-dev
    ports:
      - "8081:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
