openapi: 3.0.0

info:
  title: ACL - Workplace Integration with CXOne
  description: LALala
  version: 0.0.1

paths:
  /:
    get:
      summary: function get app
      responses:
        '200':
          description: Server Webhook Bell-DFO UP!
        '500':
          description: Catch of send
  /Webhook_App:
    get:
      summary: function get app
      responses:
        '200':
          description: return get
    post:
      summary: function post app
      responses:
        '200':
          description: return post
  /AddAction:
    get:
      summary: function get app
      responses:
        '200':
          description: return get
  /RemoveAction:
    get:
      summary: function get app
      responses:
        '200':
          description: return get
  /IntegrationBox/1.0/token:
    post:
      summary: function get app
      responses:
        '200':
          description: return get
  //IntegrationBox/1.0/posts/:postId([0-9-a-z]{36})/messages:
    post:
      summary: function get app
      responses:
        '200':
          description: return get
