comment on table remove.clients is 'Tabla de registros de clientes';
comment on table remove.clients_alerts_messages is 'Tabla de registros de notificaciones de clientes';
comment on table remove.clients_audit_access is 'Tabla de registros de historial de actividades de clientes';
comment on table remove.clients_email_verification_requests is 'Tabla de registros de solicitudes de verificaciones de correos de clientes';
comment on table remove.clients_passwords is 'Tabla de registros de contraseñas de clientes';
comment on table remove.clients_passwords_change_requests is 'Tabla de registros de solicitudes de cambios de contraseñas';
comment on table remove.clients_paybills is 'Tabla de registros de facturas de clientes';
comment on table remove.clients_payment_keys is 'Tabla de registros claves de pagos de clientes';
comment on table remove.clients_plans is 'Tabla de registros de suscripciones de clientes';
comment on table remove.clients_plans_migrations is 'Tabla de registros de cambios de planes de clientes';
comment on table remove.clients_sessions is 'Tabla de registros de sesiones clientes';
comment on table remove.clients_suscriptions_attempts is 'Tabla de registros de intentos de suscripciones de clientes';
comment on table remove.configurations is 'Tabla de registros de configuración del sistema';
comment on table remove.countries is 'Tabla de registros de paises';
comment on table remove.deindexations is 'Tabla principal de registros de desindexaciones';
comment on table remove.deindexations_files_evidences is 'Tabla de registros de información de archivos de evidencias de desindexaciones';
comment on table remove.deindexations_historic is 'Tabla de registros de historial de actividades de desindexaciones';
comment on table remove.deindexations_input_values is 'Tabla de registros de valores de inputs de campos dinámicos de desindexaciones';
comment on table remove.deindexations_results is 'Tabla de registros de resultados o conclusiones de las desindexaciones';
comment on table remove.deindexations_urls is 'Tabla de registros de url a desindexar en las desindexaciones';
comment on table remove.dynamic_forms is 'Tabla de registros de formularios dinámicos';
comment on table remove.dynamic_forms_conditions_results is 'Tabla de registros de condiciones de resultados en los formularios dinámicos';
comment on table remove.dynamic_forms_conditions_results_labels is 'Tabla de registros de etiquetas de los resultados en los formularios dinámicos';
comment on table remove.dynamic_forms_input is 'Tabla de registros de campos de formularios dinámicos';
comment on table remove.dynamic_forms_input_description is 'Tabla de registros de etiquetas de descripcion de los campos en los formularios dinámicos';
comment on table remove.dynamic_forms_input_labels is 'Tabla de registros de etiquetas de los campos en los formularios dinámicos';
comment on table remove.dynamic_forms_input_options is 'Tabla de registros de opciones en los campos en los formularios dinámicos';
comment on table remove.dynamic_forms_input_options_labels is 'Tabla de registros de etiquetas de las opciones en campos en los formularios dinámicos';
comment on table remove.dynamic_forms_section is 'Tabla de registros de secciones de los formularios dinámicos';
comment on table remove.dynamic_forms_section_labels is 'Tabla de registros de de las etiquetas de las secciones de los formularios dinámicos';
comment on table remove.forbidden_words is 'Tabla de registros de palabras prohibidas en los escáneres';
comment on table remove.languages is 'Tabla de registros de idiomas';
comment on table remove.plans is 'Tabla de registros de planes';
comment on table remove.plans_clients_suggestions is 'Tabla de registros de sugerencias de planes hacia los clientes';
comment on table remove.plans_external_key is 'Tabla de registros de claves externas de registro de planes a plataformas de pagos';
comment on table remove.scanners is 'Tabla de registros de escáneres';
comment on table remove.scanners_configuration is 'Tabla de registros de configuraciones de escáneres';
comment on table remove.scanners_configuration_countries is 'Tabla de registros de paises en las configuraciones de escáneres';
comment on table remove.scanners_impulses is 'Tabla de registros de impulsos';
comment on table remove.scanners_impulses_contents is 'Tabla de registros de contenido de los impulsos';
comment on table remove.scanners_impulses_interactions is 'Tabla de registros de interacciones con los impulsos';
comment on table remove.scanners_impulses_observations is 'Tabla de registros de obsevaciones de los impulsos';
comment on table remove.scanners_impulses_variables is 'Tabla de registros de variables de interacciones con los impulsos';
comment on table remove.scanners_keywords is 'Tabla de registros de palabras claves de los escáneres';
comment on table remove.scanners_results is 'Tabla de registros de resultados de consulta de los escáneres a la API de SERP';
comment on table remove.scanners_results_images_snippets is 'Tabla de registros de resultados de imagenes en los escáneres';
comment on table remove.scanners_results_images_snippets_keyword_tw is 'Tabla de registros de palabras de rastreo encontradas en los resultados de imagenes de los escáneres';
comment on table remove.scanners_results_images_snippets_tracks is 'Tabla de registros de posicionamientos de los resultados de imagenes de los escáneres';
comment on table remove.scanners_results_news_snippets is 'Tabla de registros de resultados de noticias en los escáneres';
comment on table remove.scanners_results_news_snippets_keyword_tw is 'Tabla de registros de palabras de rastreo encontradas en los resultados de noticias de los escáneres';
comment on table remove.scanners_results_news_snippets_tracks is 'Tabla de registros de posicionamientos de los resultados de noticias de los escáneres';
comment on table remove.scanners_results_raw is 'Tabla de registros de respaldo de los resultados planos de consulta de los escáneres a la API de SERP';
comment on table remove.scanners_results_views is 'Tabla de registros de última modificacion de escáneres para facilitar la carga en los servicios de vista';
comment on table remove.scanners_results_web_snippets is 'Tabla de registros de resultados de todo en los escáneres';
comment on table remove.scanners_results_web_snippets_tracks is 'Tabla de registros de posicionamientos de los resultados de todo de los escáneres';
comment on table remove.scanners_results_web_snippets_tw is 'Tabla de registros de palabras de rastreo encontradas en los resultados de todo de los escáneres';
comment on table remove.scanners_suscriptions_historics is 'Tabla de registros de historial de suscripciones a escáneres';
comment on table remove.scanners_tracking_words is 'Tabla de registros de palabras de rastreo en las configuraciones de los escáneres';
comment on table remove.schemas_tools_executed is 'Tabla de registros de queries ejecutados de forma automática en la base de datos';
comment on table remove.tracking_words is 'Tabla de registros de palabras de rastreo';
comment on table remove.users is 'Tabla de registros de usuarios';
comment on table remove.users_alerts_messages is 'Tabla de registros de notificaciones de usuarios';
comment on table remove.users_audit_access is 'Tabla de registros de historial de actividades de usuarios';
comment on table remove.users_clients is 'Tabla de registros de clientes asociados a usuarios';
comment on table remove.users_passwords is 'Tabla de registros de contraseñas de usuarios';
comment on table remove.users_passwords_change_requests is 'Tabla de registros de solicitudes de cambios de contraseñas';
comment on table remove.users_sessions is 'Tabla de registros de sesiones de usuarios';